### ISSUE TITLE
Big Thumbs up

### ISSUE THREAD

**Issue by cake2** [curtbraz/WhosHere#11]
The installation is really tricky but I confirm it still does work 2020. (kali raspi 1b)

I only have one small problem left and am going to let it go since everything seems to work:
I get `[Warning] Aborted connection 2210 to db: 'WhosHere' user: 'whoshere' host: 'localhost' (Got an error reading communication packets)` in /var/log/mysql/error.log
The ITTT works, database and webpage gets populated, everything starts up ok.

If anyone else is having trouble, open the Install.sh file and go through it line by line.
I found I needed to put my wlan (mon0) interface into 2.412G mode to listen to traffic in my area. (iwconfig) it was on 5G.
If I had the skill to improve on this I would, but hope someone else does and will. Thanks Curt for sharing.

edit: 

- tshark (wireshark) changed the name of wlan_mgt.ssid to wlan.ssid after version 2.2.17 
  So I changed that in line 22 of run.py

- From a fresh raspbian install I needed "apt install apache2 php php7.3-mysqlnd mariadb-server mariadb-client python-mysqldb tshark  python-pymysql"
Not sure if I needed python3-pymysql but it too was installed

- I pasted the whole url webhook in when running INSTALL.sh when I think I should only have entered the key part.

**Comment by ghost** [comment]
Great write up, thank you.

If you wouldn't mind, let us know how well it works with devices that never connect to the network.  What kinds of identification can you do on them?  How precise can you be when it comes to "fingerprinting" devices.

Any commentary would be appreciated.

**Comment by cake2** [comment]
I have noticed some devices are very, very noisy, others only sending out a probe request every few minutes. I noticed this depends on if the device is currently connected to a AP and its type/model, seems different phones models vary quiet a bit on the timing of the probe packets. One issue that is mentioned in the README is about the random MAC address. I have one such device showing up. It spams the web interface, so I would like to change that so only on the second probe packet from same MAC it gets logged, alerts and displayed. The device that I believe has that function sends just 1 packet and then on the next probe packet it has a different device ID MAC, but same OUI. Really spams it up. This tool from curtbraz displays any SSID the device was probing for also (The saved networks in android).

**Comment by curtbraz** [comment]
Hey it's good to hear from you both and I'm glad there's still use for this tool!  Things are slowing down a bit for me in my day job so I'm thinking about getting back into improving this.  I'd love to set this up either in docker or Python3 self-contained packages so installation is easier.  Also, I never got around to implementing that hack to bypass MAC randomization, might look at that and clean up the UI a bit as well.  Stay tuned!

**Comment by curtbraz** [comment]
Okay I just wiped my Raspberry Pi 3 and ran through the installation myself.  I've updated the INSTALL.sh script and run.py to fix some issues with newer versions.  All seems to work well for me now.  I'll plan on adding new features within the next couple of weeks!
