### ISSUE TITLE
A tiny miss in the install code?

### ISSUE THREAD

**Issue by NoseMith** [curtbraz/WhosHere#4]
Hey Buddy, hope all is good!

In the` install.sh` code on line 92, I think there is an error, it should be `dbconfig.php` not `dbconfig.py` right?

Happy Easter!

**Comment by curtbraz** [comment]
Hey @NoseMith!  Thank you.  While I'd love to say it was some kind of Easter Egg I put in the code, I just plain goofed.  I appreciate you pointing it out!
