### ISSUE TITLE
Installation on Kali Linux

### ISSUE THREAD

**Issue by ghost** [curtbraz/WhosHere#5]
./INSTALL.sh   
Initiating Install..
Updating Repositories..
Hit:1 http://linux.teamviewer.com/deb stable InRelease
Hit:2 http://linux.teamviewer.com/deb preview InRelease                                           
Hit:3 http://archive-3.kali.org/kali kali-rolling InRelease                                       
Reading package lists... Done
Installing Required Packages.. You Will Have to Create a Database Password if Installing MySQL For the First Time..
Reading package lists... Done
Building dependency tree       
Reading state information... Done
Package mysql-client is not available, but is referred to by another package.
This may mean that the package is missing, has been obsoleted, or
is only available from another source

Package php5 is not available, but is referred to by another package.
This may mean that the package is missing, has been obsoleted, or
is only available from another source

Package mysql-server is not available, but is referred to by another package.
This may mean that the package is missing, has been obsoleted, or
is only available from another source

Package mysql-server-5.5 is not available, but is referred to by another package.
This may mean that the package is missing, has been obsoleted, or
is only available from another source
However the following packages replace it:
  mariadb-server-10.1:i386 mysql-common mariadb-server-10.1

Package php5-mysqlnd is not available, but is referred to by another package.
This may mean that the package is missing, has been obsoleted, or
is only available from another source

E: Package 'php5' has no installation candidate
E: Package 'mysql-client' has no installation candidate
E: Package 'mysql-server-5.5' has no installation candidate
E: Package 'php5-mysqlnd' has no installation candidate
E: Package 'mysql-server' has no installation candidate

After setup when I try to run:

 python ./run.py
Traceback (most recent call last):
  File "./run.py", line 9, in <module>
    db="WhosHere")
  File "/usr/local/lib/python2.7/dist-packages/pymysql/__init__.py", line 90, in Connect
    return Connection(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/pymysql/connections.py", line 699, in __init__
    self.connect()
  File "/usr/local/lib/python2.7/dist-packages/pymysql/connections.py", line 936, in connect
    self._request_authentication()
  File "/usr/local/lib/python2.7/dist-packages/pymysql/connections.py", line 1156, in _request_authentication
    auth_packet = self._read_packet()
  File "/usr/local/lib/python2.7/dist-packages/pymysql/connections.py", line 1018, in _read_packet
    packet.check_error()
  File "/usr/local/lib/python2.7/dist-packages/pymysql/connections.py", line 384, in check_error
    err.raise_mysql_exception(self._data)
  File "/usr/local/lib/python2.7/dist-packages/pymysql/err.py", line 107, in raise_mysql_exception
    raise errorclass(errno, errval)
pymysql.err.InternalError: (1698, u"Access denied for user 'root'@'localhost'")

Setting Up the Web Server..
Configuring MySQL Server and WhosHere Database..
Enter password: 
ERROR 1049 (42000): Unknown database 'WhosHere'
Setting up Scheduled Cron Jobs and Autostart Background Services..
Installation Complete!  Visit "http://localhost/WhosHere" to Begin!

I would like to make this project work, can you provide some insight ?

All the best

**Comment by curtbraz** [comment]
Hello!

I'm happy to help.  Are you running this on a Raspberry Pi?  If so, what
Distro?

Thanks,

**Comment by ghost** [comment]
I tried it on a laptop and a Rpi3. Both machines are running Kali Linux 2018.

**Comment by ghost** [comment]
Also one suggestion, I have noticed that your script once loaded adds reminders to cron tab and this can consume a lot of CPU power whiles running. It took my a day to find out the cause of high CPU usage, just a suggestion a not a complaint ;) . Thanks!

In a retrospect I should have looked at post installation message it would shave few hours of my search ;)

**Comment by forrp2** [comment]
Just starting here, but I'm also having similar/same issues installing Whoshere on Kali Linux on Raspberry Pi3 B+

The Whoshere service exits with error.

app-get xxxxx line in INSTALL.sh gives same 5 (above) package warning messages.

Is there an alternative set of setup docs for Kali with Raspberry?

**Comment by forrp2** [comment]
Is this project active?

**Comment by curtbraz** [comment]
Hey all, I finally had some "free time" to look back at this project.  Several things have changed and broke my installer script.  I believe I have it all fixed, but if you've already partially installed you'll want to remove and re-clone/install.  

To remove, `rm -rf /home/pi/WhosHere; rm -rf /var/www/html/WhosHere; rm /lib/systemd/system/whoshere.service; apt-get remove mysql-server;`

**Comment by forrp2** [comment]
Thanks, hopefully a good use of "free time"

Using Kali linux (because my wifi adapter is better supported), I made a fresh image and tried installation on a virgin Pi.

The install still complains about mysql-client, mysql-server, php-mysqlnd.  I worked past these errors once before, so I will try again.

If I'm successful, I'll share.

Thanks for updating the repo.

**Comment by curtbraz** [comment]
Thanks!  Yes, please do.  I'll have to try with Kali myself, so far only
with the newest Raspbian distro.

**Comment by forrp2** [comment]
I gave it a second try after dinner.  Its one heck of a technical knot on Kali. I managed to get past  6 or so issues referring to google search results, but so far it's a game of whack-a-mole and something else breaks.

Real too bad, I'm running out of time.  

Would you know of another solution to use Wifi IDs as presence sensor in to IoT ?

Looks like a mysql db issue is next issue to tackle.

![image](https://user-images.githubusercontent.com/13340057/45261494-b5c8f300-b3b8-11e8-820d-c11078ce883c.png)



`python run.py
Traceback (most recent call last):
  File "run.py", line 9, in <module>
    db="WhosHere")

  File "/usr/local/lib/python2.7/dist-packages/pymysql/__init__.py", line 94, in Connect
    return Connection(*args, **kwargs)

  File "/usr/local/lib/python2.7/dist-packages/pymysql/connections.py", line 327, in __i                     nit__
    self.connect()

  File "/usr/local/lib/python2.7/dist-packages/pymysql/connections.py", line 629, in con                     nect
    raise exc

pymysql.err.OperationalError: (2003, "Can't connect to MySQL server on 'localhost' ([Err                     no 111] Connection refused)")
`

and this
` mysql -u whoshere -p

Enter password:

ERROR 2002 (HY000): Can't connect to local MySQL server through socket '/var/run/mysqld/mysqld.sock' (111 "Co                            nnection refused")
`


[var log mysql error.log.txt](https://github.com/curtbraz/WhosHere/files/2364022/var.log.mysql.error.log.txt)



root@kali:/home/Pi/WhosHere# mysql -u whoshere -p
Enter password:
Welcome to the MariaDB monitor.  Commands end with ; or \g.
Your MariaDB connection id is 118
Server version: 10.1.35-MariaDB-1 Debian buildd-unstable

Copyright (c) 2000, 2018, Oracle, MariaDB Corporation Ab and others.

Type 'help;' or '\h' for help. Type '\c' to clear the current input statement.

MariaDB [(none)]> connect WhosHere
Reading table information for completion of table and column names
You can turn off this feature to get a quicker startup with -A

Connection id:    292
Current database: WhosHere

MariaDB [WhosHere]>

---
MariaDB [(none)]> connect WhosHere
Reading table information for completion of table and column names
You can turn off this feature to get a quicker startup with -A

Connection id:    124
Current database: WhosHere

MariaDB [WhosHere]> show tables;
ERROR 2013 (HY000): Lost connection to MySQL server during query
MariaDB [WhosHere]>

**Comment by curtbraz** [comment]
Sorry, I'm not aware of another solution and I unfortunately don't have the
time myself to make it compatible with multiple Linux distros.  This was
meant to be an RPi project.  That being said, you might try Debian because
at one point I recall getting it to run on Ubuntu.  Good luck!

**Comment by forrp2** [comment]
Thanks,
I tried on Raspbian and Kali. Neither worked.
I'm giving up. It is too much to figure out.

**Comment by curtbraz** [comment]
Sounds good
